In [1]:
import pandas as pd

In [2]:
# Load all sheets from Excel file

socio21_22 = pd.ExcelFile("C:/Users/g.bouwou/OneDrive/DEVELOPPEMENT COMMUNAUTAIRE 21-22/SOCIO-ECO 21-22(1).xlsx")

In [3]:
# First group of socio-eco sheets
selected_sheetssocio21_22 = ["SOCIO-ECO(1)", "SOCIO-ECO(2)"]  


# Read and concatenate
df_listsocio21_22 = [socio21_22.parse(name) for name in selected_sheetssocio21_22]
dfsocio = pd.concat(df_listsocio21_22, ignore_index=True)

In [4]:
socio21_222 = pd.ExcelFile("C:/Users/g.bouwou/OneDrive/DEVELOPPEMENT COMMUNAUTAIRE 21-22/SOCIO-ECO 21-22(2).xlsx")

In [5]:

# Second group of sheets
selected_sheetssocio2 = ["SOCIO-ECO(1)", "SOCIO-ECO(2)"]
df_listsocio2 = [socio21_222.parse(name) for name in selected_sheetssocio2]
df_more = pd.concat(df_listsocio2, ignore_index=True)  # another batch of data

In [6]:

# Append to the original dfsocio
dfsocio = pd.concat([dfsocio, df_more], ignore_index=True)

In [8]:
socio22_23 = pd.ExcelFile("C:/Users/g.bouwou/OneDrive/DEVELOPPEMENT COMMUNAUTAIRE 22-23/SOCIO-ECO 22-23.xlsx")

In [9]:
# Third group of sheets
selected_sheetssocio3 = ["SOCIO-ECO"]
df_socio3 = socio22_23.parse("SOCIO-ECO")

In [10]:

# Then concatenate it with the previous one
dfsocio = pd.concat([dfsocio, df_socio3], ignore_index=True)

In [11]:
socio23_24 = pd.ExcelFile("C:/Users/g.bouwou/OneDrive/DEVELOPPEMENT COMMUNAUTAIRE 23-24/SOCIO-ECO 23-24.xlsx")

In [12]:

#Fourth group of sheets
selected_sheetssocio4 = ["SOCIO-ECO(1)","SOCIO-ECO(2)"]
df_listsocio3 = [socio23_24.parse(name) for name in selected_sheetssocio4]
df_more = pd.concat(df_listsocio3, ignore_index=True)  # another batch of data

In [13]:
# Append to the original dfsocio
dfsocio = pd.concat([dfsocio, df_more], ignore_index=True)

In [14]:
# Load all sheets from Excel file

hh21_22 = pd.ExcelFile("C:/Users/g.bouwou/OneDrive/DEVELOPPEMENT COMMUNAUTAIRE 21-22/CLMRS Household profiling 21-22.xlsx")

In [15]:
# First group of HH profiling sheets
selected_sheetshh21_22 = ["CLMRS HH 21-22(1)", "CLMRS HH 21-22(2)","CLMRS HH 21-22(3)","CLMRS HH 21-22(4)"]  
selected_sheetshhc21_22 = ["ROSTER_CHILDREN(1)", "ROSTER_CHILDREN(2)","ROSTER_CHILDREN(3)","ROSTER_CHILDREN(4)"]  
selected_sheetshhh21_22 = ["ROSTER_HEAVY(1)", "ROSTER_HEAVY(2)","ROSTER_HEAVY(3)","ROSTER_HEAVY(4)"] 
selected_sheetshhl21_22 = ["ROSTER_WORKLIGHT(1)", "ROSTER_WORKLIGHT(2)","ROSTER_WORKLIGHT(3)","ROSTER_WORKLIGHT(4)"] 


# Read and concatenate
df_listhh21_22 = [hh21_22.parse(name) for name in selected_sheetshh21_22]

df_listhhc21_22 = [hh21_22.parse(name) for name in selected_sheetshhc21_22]

df_listhhh21_22 = [hh21_22.parse(name) for name in selected_sheetshhh21_22]

df_listhhl21_22 = [hh21_22.parse(name) for name in selected_sheetshhl21_22]

dfhh = pd.concat(df_listhh21_22, ignore_index=True)

dfhhc = pd.concat(df_listhhc21_22, ignore_index=True)

dfhhh = pd.concat(df_listhhh21_22, ignore_index=True)

dfhhl = pd.concat(df_listhhl21_22, ignore_index=True)

In [16]:
hh22_23 = pd.ExcelFile("C:/Users/g.bouwou/OneDrive/DEVELOPPEMENT COMMUNAUTAIRE 22-23/CLMRS Household Profiling 22-23.xlsx")

In [17]:
# Second group of HH profiling sheets
selected_sheetshh22_23 = ["HH_profiling(1)", "HH_profiling(2)","HH_profiling(3)","HH_profiling(4)"]  
selected_sheetshhc22_23 = ["ROSTER_CHILDREN(1)", "ROSTER_CHILDREN(2)","ROSTER_CHILDREN(3)","ROSTER_CHILDREN(4)"]  
selected_sheetshhh22_23 = ["ROSTER_HEAVY(1)", "ROSTER_HEAVY(2)","ROSTER_HEAVY(3)","ROSTER_HEAVY(4)"] 
selected_sheetshhl22_23 = ["ROSTER_WORKLIGHT(1)", "ROSTER_WORKLIGHT(2)","ROSTER_WORKLIGHT(3)","ROSTER_WORKLIGHT(4)"]

In [18]:
# Read and concatenate
df_listhh22_23 = [hh22_23.parse(name) for name in selected_sheetshh22_23]

df_listhhc22_23 = [hh22_23.parse(name) for name in selected_sheetshhc22_23]

df_listhhh22_23 = [hh22_23.parse(name) for name in selected_sheetshhh22_23]

df_listhhl22_23 = [hh22_23.parse(name) for name in selected_sheetshhl22_23]

df_morehh = pd.concat(df_listhh22_23, ignore_index=True)  # another batch of data

df_morehhc = pd.concat(df_listhhc22_23, ignore_index=True)  # another batch of data

df_morehhh = pd.concat(df_listhhh22_23, ignore_index=True)  # another batch of data

df_morehhl = pd.concat(df_listhhl22_23, ignore_index=True)  # another batch of data

In [19]:
# Append to the original dfhh
dfhh = pd.concat([dfhh, df_morehh], ignore_index=True)

dfhhc = pd.concat([dfhhc, df_morehh], ignore_index=True)

dfhhh = pd.concat([dfhhh, df_morehhh], ignore_index=True)

dfhhl = pd.concat([dfhhl, df_morehhl], ignore_index=True)

In [20]:
hh23_24 = pd.ExcelFile("C:/Users/g.bouwou/OneDrive/DEVELOPPEMENT COMMUNAUTAIRE 23-24/CLMRS Household profiling 23-24.xlsx")

In [21]:
# Third group of HH profiling sheets
selected_sheetshh23_24 = ["HH_profiling"] 
selected_sheetshhc23_24 = ["ROSTER_CHILDREN"] 
selected_sheetshhh23_24 = ["ROSTER_HEAVY"] 
selected_sheetshhl23_24 = ["ROSTER_WORKLIGHT"]

In [23]:
dfhh3 = hh23_24.parse("HH_profiling")
dfhhc3 = hh23_24.parse("ROSTER_CHILDREN")
dfhhh3 = hh23_24.parse("ROSTER_HEAVY")
dfhhl3 = hh23_24.parse("ROSTER_WORKLIGHT")

In [24]:
# Then concatenate it with the previous one
dfhh = pd.concat([dfhh, dfhh3], ignore_index=True)
dfhhc = pd.concat([dfhhc, dfhhc3], ignore_index=True)
dfhhh = pd.concat([dfhhh, dfhhh3], ignore_index=True)
dfhhl = pd.concat([dfhhl, dfhhl3], ignore_index=True)

In [25]:
# Then concatenate it with the previous one
dfhh_ = pd.concat([dfhh, dfhh3], ignore_index=True)
dfhhc_ = pd.concat([dfhhc, dfhhc3], ignore_index=True)
dfhhh_ = pd.concat([dfhhh, dfhhh3], ignore_index=True)
dfhhl_ = pd.concat([dfhhl, dfhhl3], ignore_index=True)

# Création de l'indicateur Child Labor

In [71]:
dfhh_

,index,interview__key,interview__id,enumerator_code,enumerator_name,SP3,SP6,farmer_code,farmer_name,farmer_first_name,...,Observations__0c,Observations__1c,Observations__2c,Observations__3c,Observations__4c,Observations__5c,Observations__6c,Observations__7c,Observations__8c,Observations__9c
0,0,08-10-67-13,b5145f8acff24a969667fc7d8ff0925f,Scpk2122_25,KOUAKOU KONAN JOHN,S.C.P.K COOP-CA,SOUBRE 3,CIV-NAW-SC120484-009-0039,SAWADOGO,IDRISSA 2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,48-39-36-38,e9729951a12b48f39b8036b2b3bf18aa,Scpk2122_25,KOUAKOU KONAN JOHN,S.C.P.K COOP-CA,SOUBRE 3,CIV-NAW-SC120484-009-0004,GNINASSE,OUMAROU,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,79-68-00-01,4a95fa3b869343579c5cc9bbb00244b4,Cajpg2122_15,KANI KABIE FULGENCE,CAJPG-SCOOPS,GOTIBO,CIV-GOH-SC090372-002-0124,TRAORE,YACOUBA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,41-43-33-51,c27def4c654c4392a8b28c17a6b0de35,Ecapr2122_9,KOUASSI YAO FRANCK,COOP-CA-ECAPR,ROBERT P,CIV-NAW-SC120162-004-0383,LOUKOU,AMENAN AGNES,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,45-87-68-22,09c175e1f5fc45f1817e25c72b91111f,Cajpg2122_20,N'GUESSAN KOFFI HYACINTHE,CAJPG-SCOOPS,LATEBRE,CIV-GOH-SC090372-005-0045,KOUASSI,KOUASSI FRANCOIS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176555,36542,29-67-37-63,1953e9422adf40378209245440354c4e,Socopdal2324_56,SEKREDOU KOBENAN FELIX,SOCOPDAL,TAGOBERI,CIV-LOH-SC070565-039-0010,DJAHA,KONAN ALPHONSE,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176556,36543,79-35-43-77,f2a96e01d2c24352834c9a2fff0a6db9,Snapal2324_45,BROU KONAN PATRICE,SNAPAL,GNAKOUBOUE,CIV-LOH-A01030107-025-0094,DADI,DJILO ISABELLE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176557,36544,17-74-17-99,d7786d3e854d4dc182cdd8896bd7b61d,Scamk2324_10,KOUAME DARCIS,SCAMK-SCOOPS,TOBLY,CIV-GUE-SC081139-002-0373,GOH,FABRICE,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176558,36545,80-92-03-21,e340eb7319a941ed82abce5ba07ca9e7,Scamk2324_10,KOUAME DARCIS,SCAMK-SCOOPS,TOBLY,CIV-GUE-SC081139-002-0092,TANKODOGO,FRANCOIS,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176559,36546,06-44-83-02,d66a260000734fd684200cdf22f14cd8,Socopdal2324_52,KONE VIVIANE EPOUSE WODJI,SOCOPDAL,TAGOLILIE,CIV-LOH-SC070565-016-0221,PALE,PEMATE,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [73]:
dfhhc_

,index,interview__key,interview__id,ROSTER_CHILDREN__id,list_children,child_available,child_not_avail__1,child_not_avail__2,child_not_avail__3,child_not_avail__4,...,Observations__9,Photo1,Photo2,Signature,End_Interview,sssys_irnd,has__errors,interview__status,assignment__id,child_idc
0,0,08-10-67-13,b5145f8acff24a969667fc7d8ff0925f,1.0,sawadogo madi,Non,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b5145f8acff24a969667fc7d8ff0925f-C1.0
1,1,48-39-36-38,e9729951a12b48f39b8036b2b3bf18aa,1.0,gninasse abdoul,Non,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,e9729951a12b48f39b8036b2b3bf18aa-C1.0
2,2,48-39-36-38,e9729951a12b48f39b8036b2b3bf18aa,2.0,gninasse oumar,Non,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,e9729951a12b48f39b8036b2b3bf18aa-C2.0
3,3,79-68-00-01,4a95fa3b869343579c5cc9bbb00244b4,1.0,TRAORÉ MAFASSA,Oui,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4a95fa3b869343579c5cc9bbb00244b4-C1.0
4,4,79-68-00-01,4a95fa3b869343579c5cc9bbb00244b4,2.0,TRAORÉ ISSOUF,Non,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4a95fa3b869343579c5cc9bbb00244b4-C2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270175,61767,29-67-37-63,1953e9422adf40378209245440354c4e,2.0,konan sephora,Non,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1953e9422adf40378209245440354c4e-C2.0
270176,61768,17-74-17-99,d7786d3e854d4dc182cdd8896bd7b61d,1.0,go ange divine,Non,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,d7786d3e854d4dc182cdd8896bd7b61d-C1.0
270177,61769,17-74-17-99,d7786d3e854d4dc182cdd8896bd7b61d,2.0,go trésor,Non,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,d7786d3e854d4dc182cdd8896bd7b61d-C2.0
270178,61770,80-92-03-21,e340eb7319a941ed82abce5ba07ca9e7,1.0,TEHE PRINCE,Oui,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,e340eb7319a941ed82abce5ba07ca9e7-C1.0
270179,61771,06-44-83-02,d66a260000734fd684200cdf22f14cd8,1.0,PALE JEAN,Oui,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,d66a260000734fd684200cdf22f14cd8-C1.0

In [74]:
dfhhh_

,index,interview__key,interview__id,ROSTER_CHILDREN__id,ROSTER_HEAVY__id,workheavy_paid,workheavy_7days,workheavy_duration_schl,workheavy_duration_we,workheavy_hours_schl,workheavy_hours_we,child_idh
0,0,71-01-75-34,28f9755e882242eca0d6cd6950bd7a13,2,Conduite d’engins motorisés,Non,Oui,1 heure,1 heure,1.0,1.0,28f9755e882242eca0d6cd6950bd7a13-C2
1,1,71-01-75-34,28f9755e882242eca0d6cd6950bd7a13,2,Port de charges lourdes ( Garçon : 14-16ans&gt...,Oui,Oui,1 heure,1 heure,1.0,1.0,28f9755e882242eca0d6cd6950bd7a13-C2
2,2,81-95-94-32,432de8cb4c704fa898aaadbedeb298e0,1,Ecabossage avec une machette ou tout autre out...,Non,Oui,Moins d'une heure,3-4 heures,1.0,6.0,432de8cb4c704fa898aaadbedeb298e0-C1
3,3,81-95-94-32,432de8cb4c704fa898aaadbedeb298e0,2,Ecabossage avec une machette ou tout autre out...,Non,Oui,Moins d'une heure,3-4 heures,1.0,6.0,432de8cb4c704fa898aaadbedeb298e0-C2
4,4,98-96-26-07,581ef8b2fe3f4c6395679a1a406ef652,1,Port de charges lourdes ( Garçon : 14-16ans&gt...,Non,Oui,Moins d'une heure,3-4 heures,0.0,2.0,581ef8b2fe3f4c6395679a1a406ef652-C1
...,...,...,...,...,...,...,...,...,...,...,...,...
56695,11582,64-52-89-86,1b2bac1fb01149f9aab5ac85ca02f8da,1,Port de charges lourdes ( Garçon : 14-16ans&gt...,Non,Oui,2 heures,2 heures,2.0,2.0,1b2bac1fb01149f9aab5ac85ca02f8da-C1
56696,11583,55-69-85-85,60883a4fd5d7444bae9b69804a0b35b7,1,Utilisation de machettes pour le désherbage o...,Non,Oui,2 heures,3-4 heures,2.0,3.0,60883a4fd5d7444bae9b69804a0b35b7-C1
56697,11584,55-69-85-85,60883a4fd5d7444bae9b69804a0b35b7,1,Abattage des arbres,Non,Oui,2 heures,2 heures,2.0,2.0,60883a4fd5d7444bae9b69804a0b35b7-C1
56698,11585,80-92-03-21,e340eb7319a941ed82abce5ba07ca9e7,1,Utilisation de machettes pour le désherbage o...,Non,Oui,2 heures,2 heures,2.0,2.0,e340eb7319a941ed82abce5ba07ca9e7-C1
56699,11586,80-92-03-21,e340eb7319a941ed82abce5ba07ca9e7,1,Abattage des arbres,Non,Oui,2 heures,2 heures,2.0,2.0,e340eb7319a941ed82abce5ba07ca9e7-C1

In [77]:
dfhhl_

,index,interview__key,interview__id,ROSTER_CHILDREN__id,ROSTER_WORKLIGHT__id,worklight_paid,worklight_duration_schl,worklight_duration_we,worklight_hours_schl,worklight_hours_we,child_idl
0,0,79-68-00-01,4a95fa3b869343579c5cc9bbb00244b4,1,"Récolter les légumineuses, les fruits et autre...",Non,Moins d'une heure,4-6 heures,1.0,6.0,4a95fa3b869343579c5cc9bbb00244b4-C1
1,1,41-43-33-51,c27def4c654c4392a8b28c17a6b0de35,1,"Ramasser et rassembler les fruits, les cabosse...",Non,Moins d'une heure,1 heure,3.0,7.0,c27def4c654c4392a8b28c17a6b0de35-C1
2,2,71-01-75-34,28f9755e882242eca0d6cd6950bd7a13,1,"laver les fèves, les fruits les légumes ou les...",Non,Moins d'une heure,Moins d'une heure,0.0,0.0,28f9755e882242eca0d6cd6950bd7a13-C1
3,3,71-01-75-34,28f9755e882242eca0d6cd6950bd7a13,2,Couvrir les produits agricoles stockés à l’aid...,Non,Moins d'une heure,Moins d'une heure,0.0,0.0,28f9755e882242eca0d6cd6950bd7a13-C2
4,4,19-42-17-11,730d64d541134d87970109ea8897d9b9,1,Ramasser du bois de chauffe,Non,Moins d'une heure,2 heures,0.0,2.0,730d64d541134d87970109ea8897d9b9-C1
...,...,...,...,...,...,...,...,...,...,...,...
85181,16215,55-69-85-85,60883a4fd5d7444bae9b69804a0b35b7,1,Ramasser du bois de chauffe,Non,2 heures,2 heures,2.0,2.0,60883a4fd5d7444bae9b69804a0b35b7-C1
85182,16216,55-69-85-85,60883a4fd5d7444bae9b69804a0b35b7,1,Déposer des boutures sur les buttes,Non,2 heures,2 heures,2.0,2.0,60883a4fd5d7444bae9b69804a0b35b7-C1
85183,16217,80-92-03-21,e340eb7319a941ed82abce5ba07ca9e7,1,"Ramasser et rassembler les fruits, les cabosse...",Non,2 heures,2 heures,2.0,2.0,e340eb7319a941ed82abce5ba07ca9e7-C1
85184,16218,80-92-03-21,e340eb7319a941ed82abce5ba07ca9e7,1,Ramasser du bois de chauffe,Non,2 heures,2 heures,2.0,2.0,e340eb7319a941ed82abce5ba07ca9e7-C1
85185,16219,80-92-03-21,e340eb7319a941ed82abce5ba07ca9e7,1,Déposer des boutures sur les buttes,Non,2 heures,2 heures,2.0,2.0,e340eb7319a941ed82abce5ba07ca9e7-C1

In [79]:
# Step 1: Deduplicate dfhh just in case (only if necessary)
#farmer_code_map = dfhh.drop_duplicates(subset='interview__id').set_index('interview__id')['farmer_code']

In [81]:
# Step 2: Map the farmer_code to the rosters
#dfhhc['farmer_code'] = dfhhc['interview__id'].map(farmer_code_map)
#dfhhh['farmer_code'] = dfhhh['interview__id'].map(farmer_code_map)
#dfhhl['farmer_code'] = dfhhl['interview__id'].map(farmer_code_map)

In [83]:
#dfhhc['child_id'] = dfhhc['farmer_code'] + '-C' + dfhhc['ROSTER_CHILDREN__id'].astype(str)
#dfhhh['child_id'] = dfhhh['farmer_code'] + '-C' + dfhhh['ROSTER_CHILDREN__id'].astype(str)
#dfhhl['child_id'] = dfhhl['farmer_code'] + '-C' + dfhhl['ROSTER_CHILDREN__id'].astype(str)

In [85]:
dfhhc_['child_idc'] = dfhhc_['interview__id'] + '-C' + dfhhc_['ROSTER_CHILDREN__id'].astype(str)
dfhhh_['child_idh'] = dfhhh_['interview__id'] + '-C' + dfhhh_['ROSTER_CHILDREN__id'].astype(str)
dfhhl_['child_idl'] = dfhhl_['interview__id'] + '-C' + dfhhl_['ROSTER_CHILDREN__id'].astype(str)

In [97]:
dfhhc_['child_idc'] = dfhhc_['child_idc'].astype(str).str.strip()
dfhhh_['child_idh'] = dfhhh_['child_idh'].astype(str).str.strip()

In [99]:
heavy_ids = set(dfhhh_['child_idh'])

In [105]:
match_count = dfhhc_['child_idc'].isin(heavy_ids).sum()
print(f"{match_count} child_idc values found in heavy_ids.")

0 child_idc values found in heavy_ids.

In [82]:
dfhhc_

,index,interview__key,interview__id,ROSTER_CHILDREN__id,list_children,child_available,child_not_avail__1,child_not_avail__2,child_not_avail__3,child_not_avail__4,...,Photo1,Photo2,Signature,End_Interview,sssys_irnd,has__errors,interview__status,assignment__id,child_idc,heavy
0,0,08-10-67-13,b5145f8acff24a969667fc7d8ff0925f,1.0,sawadogo madi,Non,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b5145f8acff24a969667fc7d8ff0925f-C1.0,no heavy
1,1,48-39-36-38,e9729951a12b48f39b8036b2b3bf18aa,1.0,gninasse abdoul,Non,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,e9729951a12b48f39b8036b2b3bf18aa-C1.0,no heavy
2,2,48-39-36-38,e9729951a12b48f39b8036b2b3bf18aa,2.0,gninasse oumar,Non,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,e9729951a12b48f39b8036b2b3bf18aa-C2.0,no heavy
3,3,79-68-00-01,4a95fa3b869343579c5cc9bbb00244b4,1.0,TRAORÉ MAFASSA,Oui,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4a95fa3b869343579c5cc9bbb00244b4-C1.0,no heavy
4,4,79-68-00-01,4a95fa3b869343579c5cc9bbb00244b4,2.0,TRAORÉ ISSOUF,Non,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4a95fa3b869343579c5cc9bbb00244b4-C2.0,no heavy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270175,61767,29-67-37-63,1953e9422adf40378209245440354c4e,2.0,konan sephora,Non,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1953e9422adf40378209245440354c4e-C2.0,no heavy
270176,61768,17-74-17-99,d7786d3e854d4dc182cdd8896bd7b61d,1.0,go ange divine,Non,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,d7786d3e854d4dc182cdd8896bd7b61d-C1.0,no heavy
270177,61769,17-74-17-99,d7786d3e854d4dc182cdd8896bd7b61d,2.0,go trésor,Non,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,d7786d3e854d4dc182cdd8896bd7b61d-C2.0,no heavy
270178,61770,80-92-03-21,e340eb7319a941ed82abce5ba07ca9e7,1.0,TEHE PRINCE,Oui,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,e340eb7319a941ed82abce5ba07ca9e7-C1.0,no heavy
270179,61771,06-44-83-02,d66a260000734fd684200cdf22f14cd8,1.0,PALE JEAN,Oui,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,d66a260000734fd684200cdf22f14cd8-C1.0,no heavy

In [84]:
dfhhc_.describe(include='all')

,index,interview__key,interview__id,ROSTER_CHILDREN__id,list_children,child_available,child_not_avail__1,child_not_avail__2,child_not_avail__3,child_not_avail__4,...,Photo1,Photo2,Signature,End_Interview,sssys_irnd,has__errors,interview__status,assignment__id,child_idc,heavy
count,270180.000000,270180,270180,218447.000000,218447,218378,114522.000000,114522.000000,114522.000000,114522.000000,...,50915,50915,50915,51733,51733.000000,51733.000000,51733,51733.000000,270180,270180
unique,NaN,81368,81368,NaN,122625,2,NaN,NaN,NaN,NaN,...,2,2,2,51289,NaN,NaN,6,NaN,208408,1
top,NaN,65-90-97-44,f1c7b512f0c8418195ff152c245f8926,NaN,OUEDRAOGO MARIAM,Non,NaN,NaN,NaN,NaN,...,Photo1__.jpg,Photo2__.jpg,Signature__.jpg,##N/A##,NaN,NaN,ApprovedByHeadquarters,NaN,d66a260000734fd684200cdf22f14cd8-C1.0,no heavy
freq,NaN,36,36,NaN,179,114522,NaN,NaN,NaN,NaN,...,50428,50421,50458,307,NaN,NaN,50900,NaN,2,270180
mean,26273.374484,NaN,NaN,1.980650,NaN,NaN,0.241648,0.010548,0.009116,0.004322,...,NaN,NaN,NaN,NaN,0.501664,0.000348,NaN,396005.912648,NaN,NaN
std,19358.147618,NaN,NaN,1.300122,NaN,NaN,0.428084,0.102162,0.095043,0.065602,...,NaN,NaN,NaN,NaN,0.288814,0.027100,NaN,121946.579710,NaN,NaN
min,0.000000,NaN,NaN,1.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,0.000003,0.000000,NaN,216441.000000,NaN,NaN
25%,8831.000000,NaN,NaN,1.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,0.252131,0.000000,NaN,231174.000000,NaN,NaN
50%,23357.000000,NaN,NaN,2.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,0.502010,0.000000,NaN,439311.000000,NaN,NaN
75%,42007.000000,NaN,NaN,2.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,0.752034,0.000000,NaN,507312.000000,NaN,NaN
max,70023.000000,NaN,NaN,18.000000,NaN,NaN,1.000000,1.000000,1.000000,1.000000,...,NaN,NaN,NaN,NaN,0.999997,4.000000,NaN,679276.000000,NaN,NaN

In [428]:
print("Sample from dfhhc_:")
print(dfhhc_['child_id'].head())

print("\nSample from dfhhh_:")
print(dfhhh_['child_id'].head())

Sample from dfhhc_:
0    b5145f8acff24a969667fc7d8ff0925f-C1.0
1    e9729951a12b48f39b8036b2b3bf18aa-C1.0
2    e9729951a12b48f39b8036b2b3bf18aa-C2.0
3    4a95fa3b869343579c5cc9bbb00244b4-C1.0
4    4a95fa3b869343579c5cc9bbb00244b4-C2.0
Name: child_id, dtype: object

Sample from dfhhh_:
0    28f9755e882242eca0d6cd6950bd7a13-C2
1    28f9755e882242eca0d6cd6950bd7a13-C2
2    432de8cb4c704fa898aaadbedeb298e0-C1
3    432de8cb4c704fa898aaadbedeb298e0-C2
4    581ef8b2fe3f4c6395679a1a406ef652-C1
Name: child_id, dtype: object

In [430]:
# Strip whitespace and ensure string format
dfhhc_['child_id'] = dfhhc_['child_id'].astype(str).str.strip()
dfhhh_['child_id'] = dfhhh_['child_id'].astype(str).str.strip()

In [76]:
matches = dfhhh_['child_idh'].isin(dfhhc_['child_idc']).sum()
print(f"Number of matching child_ids: {matches}")

Number of matching child_ids: 0

In [434]:
# Create the 'heavy' column in dfhhc
dfhhc['heavy'] = dfhhc['child_id'].isin(dfhhh['child_id']).map({True: 'heavy', False: 'no heavy'})

KeyError: 'child_id'

In [280]:
dfhhc

,index,interview__key,interview__id,ROSTER_CHILDREN__id,list_children,child_available,child_not_avail__1,child_not_avail__2,child_not_avail__3,child_not_avail__4,...,Photo1,Photo2,Signature,End_Interview,sssys_irnd,has__errors,interview__status,assignment__id,child_id,heavy
0,0,08-10-67-13,b5145f8acff24a969667fc7d8ff0925f,1.0,sawadogo madi,Non,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b5145f8acff24a969667fc7d8ff0925f-C1.0,no heavy
1,1,48-39-36-38,e9729951a12b48f39b8036b2b3bf18aa,1.0,gninasse abdoul,Non,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,e9729951a12b48f39b8036b2b3bf18aa-C1.0,no heavy
2,2,48-39-36-38,e9729951a12b48f39b8036b2b3bf18aa,2.0,gninasse oumar,Non,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,e9729951a12b48f39b8036b2b3bf18aa-C2.0,no heavy
3,3,79-68-00-01,4a95fa3b869343579c5cc9bbb00244b4,1.0,TRAORÉ MAFASSA,Oui,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4a95fa3b869343579c5cc9bbb00244b4-C1.0,no heavy
4,4,79-68-00-01,4a95fa3b869343579c5cc9bbb00244b4,2.0,TRAORÉ ISSOUF,Non,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4a95fa3b869343579c5cc9bbb00244b4-C2.0,no heavy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208403,61767,29-67-37-63,1953e9422adf40378209245440354c4e,2.0,konan sephora,Non,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1953e9422adf40378209245440354c4e-C2.0,no heavy
208404,61768,17-74-17-99,d7786d3e854d4dc182cdd8896bd7b61d,1.0,go ange divine,Non,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,d7786d3e854d4dc182cdd8896bd7b61d-C1.0,no heavy
208405,61769,17-74-17-99,d7786d3e854d4dc182cdd8896bd7b61d,2.0,go trésor,Non,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,d7786d3e854d4dc182cdd8896bd7b61d-C2.0,no heavy
208406,61770,80-92-03-21,e340eb7319a941ed82abce5ba07ca9e7,1.0,TEHE PRINCE,Oui,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,e340eb7319a941ed82abce5ba07ca9e7-C1.0,no heavy
208407,61771,06-44-83-02,d66a260000734fd684200cdf22f14cd8,1.0,PALE JEAN,Oui,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,d66a260000734fd684200cdf22f14cd8-C1.0,no heavy

,index,interview__key,interview__id,ROSTER_CHILDREN__id,list_children,child_available,child_not_avail__1,child_not_avail__2,child_not_avail__3,child_not_avail__4,...,Photo1,Photo2,Signature,End_Interview,sssys_irnd,has__errors,interview__status,assignment__id,child_id,heavy
count,208408.000000,208408,208408,156675.000000,156675,156617,83307.000000,83307.000000,83307.000000,83307.000000,...,50915,50915,50915,51733,51733.000000,51733.000000,51733,51733.000000,208408,208408
unique,NaN,81368,81368,NaN,122625,2,NaN,NaN,NaN,NaN,...,2,2,2,51289,NaN,NaN,6,NaN,208408,1
top,NaN,38-26-90-52,86f2dea5597d4c66a2ce355e69ef1668,NaN,OUEDRAOGO MARIAM,Non,NaN,NaN,NaN,NaN,...,Photo1__.jpg,Photo2__.jpg,Signature__.jpg,##N/A##,NaN,NaN,ApprovedByHeadquarters,NaN,b5145f8acff24a969667fc7d8ff0925f-C1.0,no heavy
freq,NaN,18,18,NaN,126,83307,NaN,NaN,NaN,NaN,...,50428,50421,50458,307,NaN,NaN,50900,NaN,1,208408
mean,24906.343384,NaN,NaN,1.997007,NaN,NaN,0.240892,0.011212,0.011152,0.004513,...,NaN,NaN,NaN,NaN,0.501664,0.000348,NaN,396005.912648,NaN,NaN
std,19580.263883,NaN,NaN,1.310943,NaN,NaN,0.427628,0.105290,0.105011,0.067031,...,NaN,NaN,NaN,NaN,0.288814,0.027100,NaN,121946.579710,NaN,NaN
min,0.000000,NaN,NaN,1.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,0.000003,0.000000,NaN,216441.000000,NaN,NaN
25%,7509.000000,NaN,NaN,1.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,0.252131,0.000000,NaN,231174.000000,NaN,NaN
50%,20847.000000,NaN,NaN,2.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,0.502010,0.000000,NaN,439311.000000,NaN,NaN
75%,39846.250000,NaN,NaN,3.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,0.752034,0.000000,NaN,507312.000000,NaN,NaN
max,70023.000000,NaN,NaN,18.000000,NaN,NaN,1.000000,1.000000,1.000000,1.000000,...,NaN,NaN,NaN,NaN,0.999997,4.000000,NaN,679276.000000,NaN,NaN

In [188]:
# Step 1: Create sets of child_ids from dfhhh and dfhhl
heavy_ids = set(dfhhh['child_id'])
light_work_ids = set(dfhhl['child_id'])

In [190]:
# Step 2: Prepare a mapping of hours worked from dfhhl
# Ensure those columns are numeric
dfhhl['worklight_hours_schl'] = pd.to_numeric(dfhhl['worklight_hours_schl'], errors='coerce')
dfhhl['worklight_hours_we'] = pd.to_numeric(dfhhl['worklight_hours_we'], errors='coerce')

In [192]:
# Set child_id as index for mapping
work_hours_map = dfhhl.set_index('child_id')[['worklight_hours_schl', 'worklight_hours_we']]

In [194]:
work_hours_map

                              worklight_hours_schl  worklight_hours_we
child_id
CIV-GOH-SC090372-002-0124-C1                   1.0                 6.0
CIV-NAW-SC120162-004-0383-C1                   3.0                 7.0
CIV-NAW-SC120162-005-0269-C1                   0.0                 0.0
CIV-NAW-SC120162-005-0269-C2                   0.0                 0.0
CIV-NAW-SC120162-005-0312-C1                   0.0                 2.0
...                                            ...                 ...
CIV-GUE-SC081139-002-0340-C1                   2.0                 2.0
CIV-GUE-SC081139-002-0340-C1                   2.0                 2.0
CIV-GUE-SC081139-002-0092-C1                   2.0                 2.0
CIV-GUE-SC081139-002-0092-C1                   2.0                 2.0
CIV-GUE-SC081139-002-0092-C1                   2.0                 2.0

[68966 rows x 2 columns]

In [196]:
# Step 3: Merge the hours info into dfhhc based on child_id (only brings in if exists)
dfhhc = dfhhc.merge(work_hours_map, how='left', left_on='child_id', right_index=True)

In [198]:
dfhhc

,index,interview__key,interview__id,ROSTER_CHILDREN__id,list_children,child_available,child_not_avail__1,child_not_avail__2,child_not_avail__3,child_not_avail__4,...,Photo2,Signature,End_Interview,sssys_irnd,has__errors,interview__status,assignment__id,child_id,worklight_hours_schl,worklight_hours_we
0,0,08-10-67-13,b5145f8acff24a969667fc7d8ff0925f,1.0,sawadogo madi,Non,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CIV-NAW-SC120484-009-0039-C1.0,NaN,NaN
1,1,48-39-36-38,e9729951a12b48f39b8036b2b3bf18aa,1.0,gninasse abdoul,Non,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CIV-NAW-SC120484-009-0004-C1.0,NaN,NaN
2,2,48-39-36-38,e9729951a12b48f39b8036b2b3bf18aa,2.0,gninasse oumar,Non,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CIV-NAW-SC120484-009-0004-C2.0,NaN,NaN
3,3,79-68-00-01,4a95fa3b869343579c5cc9bbb00244b4,1.0,TRAORÉ MAFASSA,Oui,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CIV-GOH-SC090372-002-0124-C1.0,NaN,NaN
4,4,79-68-00-01,4a95fa3b869343579c5cc9bbb00244b4,2.0,TRAORÉ ISSOUF,Non,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CIV-GOH-SC090372-002-0124-C2.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208403,61767,29-67-37-63,1953e9422adf40378209245440354c4e,2.0,konan sephora,Non,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CIV-LOH-SC070565-039-0010-C2.0,NaN,NaN
208404,61768,17-74-17-99,d7786d3e854d4dc182cdd8896bd7b61d,1.0,go ange divine,Non,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CIV-GUE-SC081139-002-0373-C1.0,NaN,NaN
208405,61769,17-74-17-99,d7786d3e854d4dc182cdd8896bd7b61d,2.0,go trésor,Non,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CIV-GUE-SC081139-002-0373-C2.0,NaN,NaN
208406,61770,80-92-03-21,e340eb7319a941ed82abce5ba07ca9e7,1.0,TEHE PRINCE,Oui,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CIV-GUE-SC081139-002-0092-C1.0,NaN,NaN
208407,61771,06-44-83-02,d66a260000734fd684200cdf22f14cd8,1.0,PALE JEAN,Oui,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CIV-LOH-SC070565-016-0221-C1.0,NaN,NaN

In [200]:
dfhhc.describe(include='all')

,index,interview__key,interview__id,ROSTER_CHILDREN__id,list_children,child_available,child_not_avail__1,child_not_avail__2,child_not_avail__3,child_not_avail__4,...,Photo2,Signature,End_Interview,sssys_irnd,has__errors,interview__status,assignment__id,child_id,worklight_hours_schl,worklight_hours_we
count,208408.000000,208408,208408,156675.000000,156675,156617,83307.000000,83307.000000,83307.000000,83307.000000,...,50915,50915,51733,51733.000000,51733.000000,51733,51733.000000,208408,0.0,0.0
unique,NaN,81368,81368,NaN,122625,2,NaN,NaN,NaN,NaN,...,2,2,51289,NaN,NaN,6,NaN,165781,NaN,NaN
top,NaN,38-26-90-52,86f2dea5597d4c66a2ce355e69ef1668,NaN,OUEDRAOGO MARIAM,Non,NaN,NaN,NaN,NaN,...,Photo2__.jpg,Signature__.jpg,##N/A##,NaN,NaN,ApprovedByHeadquarters,NaN,TEST-Cnan,NaN,NaN
freq,NaN,18,18,NaN,126,83307,NaN,NaN,NaN,NaN,...,50421,50458,307,NaN,NaN,50900,NaN,96,NaN,NaN
mean,24906.343384,NaN,NaN,1.997007,NaN,NaN,0.240892,0.011212,0.011152,0.004513,...,NaN,NaN,NaN,0.501664,0.000348,NaN,396005.912648,NaN,NaN,NaN
std,19580.263883,NaN,NaN,1.310943,NaN,NaN,0.427628,0.105290,0.105011,0.067031,...,NaN,NaN,NaN,0.288814,0.027100,NaN,121946.579710,NaN,NaN,NaN
min,0.000000,NaN,NaN,1.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,0.000003,0.000000,NaN,216441.000000,NaN,NaN,NaN
25%,7509.000000,NaN,NaN,1.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,0.252131,0.000000,NaN,231174.000000,NaN,NaN,NaN
50%,20847.000000,NaN,NaN,2.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,0.502010,0.000000,NaN,439311.000000,NaN,NaN,NaN
75%,39846.250000,NaN,NaN,3.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,0.752034,0.000000,NaN,507312.000000,NaN,NaN,NaN
max,70023.000000,NaN,NaN,18.000000,NaN,NaN,1.000000,1.000000,1.000000,1.000000,...,NaN,NaN,NaN,0.999997,4.000000,NaN,679276.000000,NaN,NaN,NaN

In [101]:
# Step 4: Define the child labor rule
def is_child_labor(row):
    age = row['child_age']
    cid = row['child_id']
    hours_week = row.get('worklight_hours_schl', 0) or 0.0
    hours_weekend = row.get('worklight_hours_we', 0) or 0.0
    total_hours = hours_week + hours_weekend

    if (cid in heavy_ids) or (cid in light_work_ids and age < 13) or (age >= 13 and (hours_week > 2.0 or hours_weekend > 4.0 or total_hours >= 10.0)):
        return 'CL'
    else:
        return 'NoCL'

In [103]:
# Step 5: Apply logic
dfhhc['child_labor'] = dfhhc.apply(is_child_labor, axis=1)

In [105]:
dfhhc

,index,interview__key,interview__id,ROSTER_CHILDREN__id,list_children,child_available,child_not_avail__1,child_not_avail__2,child_not_avail__3,child_not_avail__4,...,End_Interview,sssys_irnd,has__errors,interview__status,assignment__id,child_id,worklight_hours_schl,worklight_hours_we,child_labor,child_labor_flag
0,0,08-10-67-13,b5145f8acff24a969667fc7d8ff0925f,1.0,sawadogo madi,Non,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,CIV-NAW-SC120484-009-0039-C1.0,NaN,NaN,NoCL,False
1,1,48-39-36-38,e9729951a12b48f39b8036b2b3bf18aa,1.0,gninasse abdoul,Non,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,CIV-NAW-SC120484-009-0004-C1.0,NaN,NaN,NoCL,False
2,2,48-39-36-38,e9729951a12b48f39b8036b2b3bf18aa,2.0,gninasse oumar,Non,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,CIV-NAW-SC120484-009-0004-C2.0,NaN,NaN,NoCL,False
3,3,79-68-00-01,4a95fa3b869343579c5cc9bbb00244b4,1.0,TRAORÉ MAFASSA,Oui,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,CIV-GOH-SC090372-002-0124-C1.0,NaN,NaN,NoCL,False
4,4,79-68-00-01,4a95fa3b869343579c5cc9bbb00244b4,2.0,TRAORÉ ISSOUF,Non,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,CIV-GOH-SC090372-002-0124-C2.0,NaN,NaN,NoCL,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208403,61767,29-67-37-63,1953e9422adf40378209245440354c4e,2.0,konan sephora,Non,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,CIV-LOH-SC070565-039-0010-C2.0,NaN,NaN,NoCL,False
208404,61768,17-74-17-99,d7786d3e854d4dc182cdd8896bd7b61d,1.0,go ange divine,Non,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,CIV-GUE-SC081139-002-0373-C1.0,NaN,NaN,NoCL,False
208405,61769,17-74-17-99,d7786d3e854d4dc182cdd8896bd7b61d,2.0,go trésor,Non,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,CIV-GUE-SC081139-002-0373-C2.0,NaN,NaN,NoCL,False
208406,61770,80-92-03-21,e340eb7319a941ed82abce5ba07ca9e7,1.0,TEHE PRINCE,Oui,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,CIV-GUE-SC081139-002-0092-C1.0,NaN,NaN,NoCL,False
208407,61771,06-44-83-02,d66a260000734fd684200cdf22f14cd8,1.0,PALE JEAN,Oui,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,CIV-LOH-SC070565-016-0221-C1.0,NaN,NaN,NoCL,False

In [107]:
# Step 1: Create a household-level child labor indicator from dfhhc
# We'll flag households where at least one child is in child labor

dfhhc['child_labor_flag'] = dfhhc['child_labor'] == 'CL'

In [109]:
# Group by interview__id and check if any child is in labor
hh_child_labor = dfhhc.groupby('interview__id')['child_labor_flag'].any().reset_index()

In [111]:
# Convert the boolean to 'Yes'/'No' or keep as boolean
hh_child_labor['child_labor_household'] = hh_child_labor['child_labor_flag'].map({True: 'Yes', False: 'No'})

In [113]:
# Step 2: Merge into dfhh
dfhh = dfhh.merge(hh_child_labor[['interview__id', 'child_labor_household']], on='interview__id', how='left')

In [115]:
# Optional: Fill NaN with 'No' if households without children should be considered as having no child labor
dfhh['child_labor_household'] = dfhh['child_labor_household'].fillna('No')

In [117]:
df_summary = dfhh[['interview__id', 'farmer_code', 'child_labor_household']].copy()

In [119]:
df_summary

,interview__id,farmer_code,child_labor_household
0,b5145f8acff24a969667fc7d8ff0925f,CIV-NAW-SC120484-009-0039,No
1,e9729951a12b48f39b8036b2b3bf18aa,CIV-NAW-SC120484-009-0004,No
2,4a95fa3b869343579c5cc9bbb00244b4,CIV-GOH-SC090372-002-0124,No
3,c27def4c654c4392a8b28c17a6b0de35,CIV-NAW-SC120162-004-0383,No
4,09c175e1f5fc45f1817e25c72b91111f,CIV-GOH-SC090372-005-0045,No
...,...,...,...
140008,1953e9422adf40378209245440354c4e,CIV-LOH-SC070565-039-0010,No
140009,f2a96e01d2c24352834c9a2fff0a6db9,CIV-LOH-A01030107-025-0094,No
140010,d7786d3e854d4dc182cdd8896bd7b61d,CIV-GUE-SC081139-002-0373,No
140011,e340eb7319a941ed82abce5ba07ca9e7,CIV-GUE-SC081139-002-0092,No
140012,d66a260000734fd684200cdf22f14cd8,CIV-LOH-SC070565-016-0221,No

In [121]:
df_cl_cases = df_summary[df_summary['child_labor_household'] == 'Yes']

In [123]:
df_cl_cases

Empty DataFrame
Columns: [interview__id, farmer_code, child_labor_household]
Index: []